name: CI

on:
  pull_request:

jobs:
  lint-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - run: uv sync
      - name: Ruff check
        run: uv run ruff check app/
      - name: Ruff format check
        run: uv run ruff format --check app/
      - name: Mypy
        run: uv run mypy app/src/
      - name: Pytest
        run: uv run pytest

  lint-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      - name: Terraform fmt
        run: terraform -chdir=terraform fmt -check -recursive
      - name: Terraform init
        run: terraform -chdir=terraform init -backend=false
      - name: Terraform validate
        run: terraform -chdir=terraform validate
      - uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
      - name: TFLint init
        run: cd terraform && tflint --init --config=.tflint.hcl
      - name: TFLint
        run: cd terraform && tflint --config=.tflint.hcl
      - name: Trivy config scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: config
          scan-ref: terraform/
          exit-code: 1
          trivyignores: terraform/.trivyignore
